import { Inter } from 'next/font/google'
import './globals.css'
import Header from '../components/Header';
import Header2 from '../components/header2';
import Herodiv from '../components/herodiv';
import Intro from '../components/intro';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Header2 />
        <Herodiv />
        <Header />
        <Intro />
        {children}
      </body>
    </html>
  )
}